### ISSUE TITLE
ブルーライトをカットする

### ISSUE THREAD

**Issue by nukosuke** [nukosuke/life#2]
ref #1 

- 寝れない原因の一つ
- スマホは夜間モードを使うと軽減可能
- 日中も目が疲れるのでブルーライトカットするメガネを買う

**Comment by ghost** [comment]
ブルーライトは諸説あるようですが、PCやスマホのディスプレイの輝度を落とすのオススメです。目が疲れにくくなります。

**Comment by nukosuke** [comment]
最近輝度を少し落として作業しています。
あと、ブルーライトカットの眼鏡を買いました。

**Comment by nukosuke** [comment]
ブルーライトカットはあまり効果が得られなかったため、最近は照度を半分以下にして運用している。
終業後の目の疲れがだいぶ改善されたように感じる。
